<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Ingredients;
class IngredientsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Ingredients::create(["name" => "Abalone", "category_id" => 12]);
        Ingredients::create(["name" => "Abiyuch", "category_id" => 18]);
        Ingredients::create(["name" => "Acerola", "category_id" => 11]);
        Ingredients::create(["name" => "Achilleas", "category_id" => 8]);
        Ingredients::create(["name" => "Acorn", "category_id" => 17]);
        Ingredients::create(["name" => "Adobo", "category_id" => 7]);
        Ingredients::create(["name" => "Adzuki bean", "category_id" => 14]);
        Ingredients::create(["name" => "Agar", "category_id" => 1]);
        Ingredients::create(["name" => "Agave", "category_id" => 18]);
        Ingredients::create(["name" => "Akutaq", "category_id" => 7]);
        Ingredients::create(["name" => "Alaska blackfish", "category_id" => 9]);
        Ingredients::create(["name" => "Alaska pollock", "category_id" => 9]);
        Ingredients::create(["name" => "Alaska wild rhubarb", "category_id" => 18]);
        Ingredients::create(["name" => "Albacore tuna", "category_id" => 9]);
        Ingredients::create(["name" => "Alfalfa", "category_id" => 13]);
        Ingredients::create(["name" => "Allium", "category_id" => 18]);
        Ingredients::create(["name" => "Allspice", "category_id" => 20]);
        Ingredients::create(["name" => "Almond", "category_id" => 17]);
        Ingredients::create(["name" => "Alpine sweetvetch", "category_id" => 18]);
        Ingredients::create(["name" => "Alpinia", "category_id" => 18]);
        Ingredients::create(["name" => "Amaranth", "category_id" => 13]);
        Ingredients::create(["name" => "American butterfish", "category_id" => 9]);
        Ingredients::create(["name" => "American pokeweed", "category_id" => 13]);
        Ingredients::create(["name" => "American shad", "category_id" => 9]);
        Ingredients::create(["name" => "Anatidae", "category_id" => 16]);
        Ingredients::create(["name" => "Anchovy", "category_id" => 9]);
        Ingredients::create(["name" => "Angelica", "category_id" => 13]);
        Ingredients::create(["name" => "Anguilliformes", "category_id" => 9]);
        Ingredients::create(["name" => "Anise", "category_id" => 20]);
        Ingredients::create(["name" => "Anise Brandy", "category_id" => 4]);
        Ingredients::create(["name" => "Anise Hyssop", "category_id" => 20]);
        Ingredients::create(["name" => "Anise Oil", "category_id" => 11]);
        Ingredients::create(["name" => "Apple", "category_id" => 11]);
        Ingredients::create(["name" => "Apple Brandy", "category_id" => 4]);
        Ingredients::create(["name" => "Apple Cider Vinegar", "category_id" => 18]);
        Ingredients::create(["name" => "Apple Juice", "category_id" => 11]);
        Ingredients::create(["name" => "Apple Sauce", "category_id" => 11]);
        Ingredients::create(["name" => "Apricot", "category_id" => 11]);
        Ingredients::create(["name" => "Arabica coffee", "category_id" => 3]);
        Ingredients::create(["name" => "Arar", "category_id" => 8]);
        Ingredients::create(["name" => "Arepa", "category_id" => 7]);
        Ingredients::create(["name" => "Armagnac Brandy", "category_id" => 4]);
        Ingredients::create(["name" => "Arrack", "category_id" => 4]);
        Ingredients::create(["name" => "Arrowhead", "category_id" => 21]);
        Ingredients::create(["name" => "Arrowroot", "category_id" => 21]);
        Ingredients::create(["name" => "Artemisia", "category_id" => 13]);
        Ingredients::create(["name" => "Artichoke", "category_id" => 10]);
        Ingredients::create(["name" => "Asafoetida", "category_id" => 20]);
        Ingredients::create(["name" => "Ascidians", "category_id" => 19]);
        Ingredients::create(["name" => "Ashgourd", "category_id" => 21]);
        Ingredients::create(["name" => "Asparagus", "category_id" => 21]);
        Ingredients::create(["name" => "Atlantic croaker", "category_id" => 9]);
        Ingredients::create(["name" => "Atlantic halibut", "category_id" => 9]);
        Ingredients::create(["name" => "Atlantic herring", "category_id" => 9]);
        Ingredients::create(["name" => "Atlantic mackerel", "category_id" => 9]);
        Ingredients::create(["name" => "Atlantic menhaden", "category_id" => 9]);
        Ingredients::create(["name" => "Atlantic pollock", "category_id" => 9]);
        Ingredients::create(["name" => "Atlantic salmon", "category_id" => 9]);
        Ingredients::create(["name" => "Atlantic wolffish", "category_id" => 9]);
        Ingredients::create(["name" => "Avocado", "category_id" => 11]);
        Ingredients::create(["name" => "Babaco", "category_id" => 11]);
        Ingredients::create(["name" => "Babassu palm", "category_id" => 18]);
        Ingredients::create(["name" => "Bagel", "category_id" => 2]);
        Ingredients::create(["name" => "Baked potato", "category_id" => 7]);
        Ingredients::create(["name" => "Baking Powder", "category_id" => 1]);
        Ingredients::create(["name" => "Bamboo shoots", "category_id" => 18]);
        Ingredients::create(["name" => "Banana", "category_id" => 11]);
        Ingredients::create(["name" => "Bantu Beer", "category_id" => 4]);
        Ingredients::create(["name" => "Barley", "category_id" => 5]);
        Ingredients::create(["name" => "Bartlett Pear", "category_id" => 11]);
        Ingredients::create(["name" => "Basil", "category_id" => 13]);
        Ingredients::create(["name" => "Basmati Rice", "category_id" => 5]);
        Ingredients::create(["name" => "Bayberry", "category_id" => 11]);
        Ingredients::create(["name" => "Beans", "category_id" => 14]);
        Ingredients::create(["name" => "Bearded seal", "category_id" => 19]);
        Ingredients::create(["name" => "Beaver", "category_id" => 16]);
        Ingredients::create(["name" => "Beech nut", "category_id" => 17]);
        Ingredients::create(["name" => "Beef", "category_id" => 16]);
        Ingredients::create(["name" => "Beef Processed", "category_id" => 16]);
        Ingredients::create(["name" => "Beefalo", "category_id" => 16]);
        Ingredients::create(["name" => "Beer", "category_id" => 4]);
        Ingredients::create(["name" => "Beetroot", "category_id" => 21]);
        Ingredients::create(["name" => "Beli", "category_id" => 11]);
        Ingredients::create(["name" => "Beluga whale", "category_id" => 9]);
        Ingredients::create(["name" => "Bergamot", "category_id" => 11]);
        Ingredients::create(["name" => "Berry wine", "category_id" => 4]);
        Ingredients::create(["name" => "Bilberry", "category_id" => 11]);
        Ingredients::create(["name" => "Bilberry Wine", "category_id" => 4]);
        Ingredients::create(["name" => "Biscuit", "category_id" => 2]);
        Ingredients::create(["name" => "Bison", "category_id" => 16]);
        Ingredients::create(["name" => "Bitter Cherry", "category_id" => 11]);
        Ingredients::create(["name" => "Bitter Orange", "category_id" => 11]);
        Ingredients::create(["name" => "Bittergourd", "category_id" => 21]);
        Ingredients::create(["name" => "Bivalvia", "category_id" => 19]);
        Ingredients::create(["name" => "Black bear", "category_id" => 16]);
        Ingredients::create(["name" => "Black crowberry", "category_id" => 11]);
        Ingredients::create(["name" => "Black Currant", "category_id" => 11]);
        Ingredients::create(["name" => "Black huckleberry", "category_id" => 11]);
        Ingredients::create(["name" => "Black mulberry", "category_id" => 11]);
        Ingredients::create(["name" => "Black raspberry", "category_id" => 11]);
        Ingredients::create(["name" => "Black salsify", "category_id" => 18]);
        Ingredients::create(["name" => "Black Tea", "category_id" => 3]);
        Ingredients::create(["name" => "Blackberry", "category_id" => 11]);
        Ingredients::create(["name" => "Blackberry Brandy", "category_id" => 4]);
        Ingredients::create(["name" => "Black-eyed pea", "category_id" => 14]);
        Ingredients::create(["name" => "Blue Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Blue whiting", "category_id" => 9]);
        Ingredients::create(["name" => "Blueberry", "category_id" => 11]);
        Ingredients::create(["name" => "Bluefish", "category_id" => 9]);
        Ingredients::create(["name" => "Bonito", "category_id" => 9]);
        Ingredients::create(["name" => "Borage", "category_id" => 13]);
        Ingredients::create(["name" => "Botrytized Wine", "category_id" => 4]);
        Ingredients::create(["name" => "Bottlegourd", "category_id" => 21]);
        Ingredients::create(["name" => "Bourbon Whisky", "category_id" => 4]);
        Ingredients::create(["name" => "Bowhead whale", "category_id" => 9]);
        Ingredients::create(["name" => "Boysenberry", "category_id" => 11]);
        Ingredients::create(["name" => "Brandy", "category_id" => 4]);
        Ingredients::create(["name" => "Brazil Nut", "category_id" => 17]);
        Ingredients::create(["name" => "Bread", "category_id" => 2]);
        Ingredients::create(["name" => "Breadfruit", "category_id" => 11]);
        Ingredients::create(["name" => "Breakfast cereal", "category_id" => 5]);
        Ingredients::create(["name" => "Broad whitefish", "category_id" => 9]);
        Ingredients::create(["name" => "Broccoli", "category_id" => 21]);
        Ingredients::create(["name" => "Brown bear", "category_id" => 16]);
        Ingredients::create(["name" => "Brown Rice", "category_id" => 5]);
        Ingredients::create(["name" => "Brussels Sprout", "category_id" => 21]);
        Ingredients::create(["name" => "Buchu", "category_id" => 8]);
        Ingredients::create(["name" => "Buckwheat", "category_id" => 13]);
        Ingredients::create(["name" => "Buffalo", "category_id" => 16]);
        Ingredients::create(["name" => "Buffalo currant", "category_id" => 11]);
        Ingredients::create(["name" => "Bulgur", "category_id" => 5]);
        Ingredients::create(["name" => "Burbot", "category_id" => 9]);
        Ingredients::create(["name" => "Burdock", "category_id" => 21]);
        Ingredients::create(["name" => "Burrito", "category_id" => 7]);
        Ingredients::create(["name" => "Butter", "category_id" => 6]);
        Ingredients::create(["name" => "Buttermilk", "category_id" => 6]);
        Ingredients::create(["name" => "Butternut", "category_id" => 17]);
        Ingredients::create(["name" => "Butternut squash", "category_id" => 11]);
        Ingredients::create(["name" => "Byrsonima crassifolia", "category_id" => 11]);
        Ingredients::create(["name" => "Cabbage", "category_id" => 21]);
        Ingredients::create(["name" => "Cajeput", "category_id" => 8]);
        Ingredients::create(["name" => "Cake", "category_id" => 7]);
        Ingredients::create(["name" => "Calamus", "category_id" => 13]);
        Ingredients::create(["name" => "Camembert Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Camphor", "category_id" => 8]);
        Ingredients::create(["name" => "Canada blueberry", "category_id" => 11]);
        Ingredients::create(["name" => "Canadian Whisky", "category_id" => 4]);
        Ingredients::create(["name" => "Candy bar", "category_id" => 2]);
        Ingredients::create(["name" => "Canola Oil", "category_id" => 8]);
        Ingredients::create(["name" => "Capers", "category_id" => 13]);
        Ingredients::create(["name" => "Capsicum", "category_id" => 21]);
        Ingredients::create(["name" => "Caraway", "category_id" => 20]);
        Ingredients::create(["name" => "Cardamom", "category_id" => 20]);
        Ingredients::create(["name" => "Cardoon", "category_id" => 18]);
        Ingredients::create(["name" => "Caribou", "category_id" => 16]);
        Ingredients::create(["name" => "Carob", "category_id" => 18]);
        Ingredients::create(["name" => "Carom Seed", "category_id" => 20]);
        Ingredients::create(["name" => "Carp bream", "category_id" => 9]);
        Ingredients::create(["name" => "Carrot", "category_id" => 21]);
        Ingredients::create(["name" => "Cascarilla", "category_id" => 8]);
        Ingredients::create(["name" => "Casein", "category_id" => 1]);
        Ingredients::create(["name" => "Cashew Apple", "category_id" => 11]);
        Ingredients::create(["name" => "Cashew nut", "category_id" => 17]);
        Ingredients::create(["name" => "Cassava", "category_id" => 21]);
        Ingredients::create(["name" => "Cassia", "category_id" => 20]);
        Ingredients::create(["name" => "Catfish", "category_id" => 9]);
        Ingredients::create(["name" => "Catjang pea", "category_id" => 14]);
        Ingredients::create(["name" => "Cauliflower", "category_id" => 21]);
        Ingredients::create(["name" => "Caviar", "category_id" => 9]);
        Ingredients::create(["name" => "Cayenne", "category_id" => 20]);
        Ingredients::create(["name" => "Cedar", "category_id" => 8]);
        Ingredients::create(["name" => "Celery", "category_id" => 20]);
        Ingredients::create(["name" => "Ceriman", "category_id" => 18]);
        Ingredients::create(["name" => "Cetacea", "category_id" => 9]);
        Ingredients::create(["name" => "Chamomile", "category_id" => 8]);
        Ingredients::create(["name" => "Champaca", "category_id" => 10]);
        Ingredients::create(["name" => "Champagne", "category_id" => 4]);
        Ingredients::create(["name" => "Channel catfish", "category_id" => 9]);
        Ingredients::create(["name" => "Chanterelle", "category_id" => 12]);
        Ingredients::create(["name" => "Chard", "category_id" => 21]);
        Ingredients::create(["name" => "Charr", "category_id" => 9]);
        Ingredients::create(["name" => "Chayote", "category_id" => 21]);
        Ingredients::create(["name" => "Cheddar Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Cherimoya", "category_id" => 11]);
        Ingredients::create(["name" => "Cherry", "category_id" => 11]);
        Ingredients::create(["name" => "Cherry Brandy", "category_id" => 4]);
        Ingredients::create(["name" => "Cherry Pepper", "category_id" => 21]);
        Ingredients::create(["name" => "Cherry tomato", "category_id" => 11]);
        Ingredients::create(["name" => "Chervil", "category_id" => 13]);
        Ingredients::create(["name" => "Chestnut", "category_id" => 17]);
        Ingredients::create(["name" => "Chewing gum", "category_id" => 7]);
        Ingredients::create(["name" => "Chia", "category_id" => 13]);
        Ingredients::create(["name" => "Chicken", "category_id" => 16]);
        Ingredients::create(["name" => "Chickpea", "category_id" => 14]);
        Ingredients::create(["name" => "Chicory", "category_id" => 18]);
        Ingredients::create(["name" => "Chimichanga", "category_id" => 7]);
        Ingredients::create(["name" => "Chinese bayberry", "category_id" => 11]);
        Ingredients::create(["name" => "Chinese chestnut", "category_id" => 17]);
        Ingredients::create(["name" => "Chinese Quince", "category_id" => 11]);
        Ingredients::create(["name" => "Chinook salmon", "category_id" => 9]);
        Ingredients::create(["name" => "Chive", "category_id" => 21]);
        Ingredients::create(["name" => "Chocolate", "category_id" => 18]);
        Ingredients::create(["name" => "Chocolate mousse", "category_id" => 2]);
        Ingredients::create(["name" => "Chocolate spread", "category_id" => 18]);
        Ingredients::create(["name" => "Chum salmon", "category_id" => 9]);
        Ingredients::create(["name" => "Cichlidae", "category_id" => 9]);
        Ingredients::create(["name" => "Cider", "category_id" => 4]);
        Ingredients::create(["name" => "Cinnamon", "category_id" => 20]);
        Ingredients::create(["name" => "Cisco", "category_id" => 9]);
        Ingredients::create(["name" => "Citric Acid", "category_id" => 1]);
        Ingredients::create(["name" => "Citronella Oil", "category_id" => 8]);
        Ingredients::create(["name" => "Citrus Fruits", "category_id" => 11]);
        Ingredients::create(["name" => "Citrus Peel Oil", "category_id" => 8]);
        Ingredients::create(["name" => "Clam", "category_id" => 19]);
        Ingredients::create(["name" => "Clary Sage", "category_id" => 8]);
        Ingredients::create(["name" => "Climbing bean", "category_id" => 14]);
        Ingredients::create(["name" => "Cloud ear fungus", "category_id" => 12]);
        Ingredients::create(["name" => "Cloudberry", "category_id" => 11]);
        Ingredients::create(["name" => "Clove", "category_id" => 20]);
        Ingredients::create(["name" => "Clupeinae", "category_id" => 9]);
        Ingredients::create(["name" => "Cluster Bean", "category_id" => 14]);
        Ingredients::create(["name" => "Cocktail", "category_id" => 3]);
        Ingredients::create(["name" => "Cocoa", "category_id" => 17]);
        Ingredients::create(["name" => "Cocoa butter", "category_id" => 18]);
        Ingredients::create(["name" => "Cocoa powder", "category_id" => 18]);
        Ingredients::create(["name" => "Coconut", "category_id" => 11]);
        Ingredients::create(["name" => "Coconut Milk", "category_id" => 3]);
        Ingredients::create(["name" => "Coconut Oil", "category_id" => 11]);
        Ingredients::create(["name" => "Codfish", "category_id" => 9]);
        Ingredients::create(["name" => "Coffee", "category_id" => 3]);
        Ingredients::create(["name" => "Coffee mocha", "category_id" => 3]);
        Ingredients::create(["name" => "Cognac Brandy", "category_id" => 4]);
        Ingredients::create(["name" => "Coho salmon", "category_id" => 9]);
        Ingredients::create(["name" => "Cold cut", "category_id" => 7]);
        Ingredients::create(["name" => "Colocasia", "category_id" => 21]);
        Ingredients::create(["name" => "Colorado pinyon", "category_id" => 18]);
        Ingredients::create(["name" => "Columbidae", "category_id" => 16]);
        Ingredients::create(["name" => "Common carp", "category_id" => 9]);
        Ingredients::create(["name" => "Common dab", "category_id" => 9]);
        Ingredients::create(["name" => "Common ling", "category_id" => 9]);
        Ingredients::create(["name" => "Common octopus", "category_id" => 19]);
        Ingredients::create(["name" => "Common persimmon", "category_id" => 11]);
        Ingredients::create(["name" => "Common salsify", "category_id" => 18]);
        Ingredients::create(["name" => "Common Tuna", "category_id" => 9]);
        Ingredients::create(["name" => "Common verbena", "category_id" => 13]);
        Ingredients::create(["name" => "Comte Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Conch", "category_id" => 9]);
        Ingredients::create(["name" => "Condensed milk", "category_id" => 6]);
        Ingredients::create(["name" => "Cooking oil", "category_id" => 1]);
        Ingredients::create(["name" => "Cooking Spray", "category_id" => 1]);
        Ingredients::create(["name" => "Coriander", "category_id" => 13]);
        Ingredients::create(["name" => "Coriander Seed", "category_id" => 21]);
        Ingredients::create(["name" => "Corn", "category_id" => 15]);
        Ingredients::create(["name" => "Corn chip", "category_id" => 2]);
        Ingredients::create(["name" => "Corn grits", "category_id" => 15]);
        Ingredients::create(["name" => "Corn Oil", "category_id" => 15]);
        Ingredients::create(["name" => "Corn salad", "category_id" => 21]);
        Ingredients::create(["name" => "Cornbread", "category_id" => 15]);
        Ingredients::create(["name" => "Cornmint", "category_id" => 13]);
        Ingredients::create(["name" => "Cottage Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Cottonseed", "category_id" => 18]);
        Ingredients::create(["name" => "Couscous", "category_id" => 7]);
        Ingredients::create(["name" => "Crab", "category_id" => 19]);
        Ingredients::create(["name" => "Cranberry", "category_id" => 11]);
        Ingredients::create(["name" => "Crayfish", "category_id" => 19]);
        Ingredients::create(["name" => "Cream", "category_id" => 6]);
        Ingredients::create(["name" => "Cream Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Creosote", "category_id" => 18]);
        Ingredients::create(["name" => "Crispbread", "category_id" => 5]);
        Ingredients::create(["name" => "Cucumber", "category_id" => 21]);
        Ingredients::create(["name" => "Cucurbita", "category_id" => 21]);
        Ingredients::create(["name" => "Cumin", "category_id" => 20]);
        Ingredients::create(["name" => "Cured Ham", "category_id" => 16]);
        Ingredients::create(["name" => "Currant", "category_id" => 11]);
        Ingredients::create(["name" => "Curry Leaf", "category_id" => 13]);
        Ingredients::create(["name" => "Cusk", "category_id" => 9]);
        Ingredients::create(["name" => "Cuttlefish", "category_id" => 9]);
        Ingredients::create(["name" => "Dandelion", "category_id" => 10]);
        Ingredients::create(["name" => "Dates", "category_id" => 11]);
        Ingredients::create(["name" => "Deer", "category_id" => 16]);
        Ingredients::create(["name" => "Deerberry", "category_id" => 11]);
        Ingredients::create(["name" => "Devilfish", "category_id" => 9]);
        Ingredients::create(["name" => "Dill", "category_id" => 13]);
        Ingredients::create(["name" => "Dock", "category_id" => 13]);
        Ingredients::create(["name" => "Dolphin fish", "category_id" => 9]);
        Ingredients::create(["name" => "Domiati Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Drag̩e", "category_id" => 7]);
        Ingredients::create(["name" => "Drumstick Leaf", "category_id" => 21]);
        Ingredients::create(["name" => "Dulce de leche", "category_id" => 6]);
        Ingredients::create(["name" => "Dumpling", "category_id" => 7]);
        Ingredients::create(["name" => "Durian", "category_id" => 11]);
        Ingredients::create(["name" => "Egg", "category_id" => 16]);
        Ingredients::create(["name" => "Egg roll", "category_id" => 7]);
        Ingredients::create(["name" => "Eggplant", "category_id" => 21]);
        Ingredients::create(["name" => "Elderberry", "category_id" => 11]);
        Ingredients::create(["name" => "Elk", "category_id" => 16]);
        Ingredients::create(["name" => "Elliott's blueberry", "category_id" => 11]);
        Ingredients::create(["name" => "Emmental Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Empanada", "category_id" => 7]);
        Ingredients::create(["name" => "Emu", "category_id" => 16]);
        Ingredients::create(["name" => "Enchilada", "category_id" => 7]);
        Ingredients::create(["name" => "Endive", "category_id" => 21]);
        Ingredients::create(["name" => "Enokitake", "category_id" => 12]);
        Ingredients::create(["name" => "Epazote", "category_id" => 13]);
        Ingredients::create(["name" => "Eucalyptus Oil", "category_id" => 8]);
        Ingredients::create(["name" => "European anchovy", "category_id" => 9]);
        Ingredients::create(["name" => "European chestnut", "category_id" => 17]);
        Ingredients::create(["name" => "European rabbit", "category_id" => 16]);
        Ingredients::create(["name" => "Evaporated milk", "category_id" => 6]);
        Ingredients::create(["name" => "Evening primrose", "category_id" => 13]);
        Ingredients::create(["name" => "Falafel", "category_id" => 7]);
        Ingredients::create(["name" => "Fatty Fish", "category_id" => 9]);
        Ingredients::create(["name" => "Feijoa", "category_id" => 11]);
        Ingredients::create(["name" => "Fennel", "category_id" => 13]);
        Ingredients::create(["name" => "Fenugreek", "category_id" => 13]);
        Ingredients::create(["name" => "Fermented Tea", "category_id" => 18]);
        Ingredients::create(["name" => "Feta Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Fig", "category_id" => 11]);
        Ingredients::create(["name" => "Filbert", "category_id" => 17]);
        Ingredients::create(["name" => "Finnish Whisky", "category_id" => 4]);
        Ingredients::create(["name" => "Fir", "category_id" => 8]);
        Ingredients::create(["name" => "Fireweed", "category_id" => 13]);
        Ingredients::create(["name" => "Fish", "category_id" => 9]);
        Ingredients::create(["name" => "Fish burger", "category_id" => 7]);
        Ingredients::create(["name" => "Fish Oil", "category_id" => 9]);
        Ingredients::create(["name" => "Flatfish", "category_id" => 9]);
        Ingredients::create(["name" => "Flaxseed", "category_id" => 17]);
        Ingredients::create(["name" => "Florida pompano", "category_id" => 9]);
        Ingredients::create(["name" => "Flour", "category_id" => 5]);
        Ingredients::create(["name" => "Focaccia", "category_id" => 2]);
        Ingredients::create(["name" => "Food Coloring", "category_id" => 1]);
        Ingredients::create(["name" => "Frankfurter Sausage", "category_id" => 7]);
        Ingredients::create(["name" => "French plantain", "category_id" => 18]);
        Ingredients::create(["name" => "French toast", "category_id" => 2]);
        Ingredients::create(["name" => "Freshwater drum", "category_id" => 9]);
        Ingredients::create(["name" => "Freshwater eel", "category_id" => 9]);
        Ingredients::create(["name" => "Fried Potato", "category_id" => 2]);
        Ingredients::create(["name" => "Fruit gum", "category_id" => 7]);
        Ingredients::create(["name" => "Fruit juice", "category_id" => 3]);
        Ingredients::create(["name" => "Fruit salad", "category_id" => 7]);
        Ingredients::create(["name" => "Frybread", "category_id" => 7]);
        Ingredients::create(["name" => "Fudge", "category_id" => 2]);
        Ingredients::create(["name" => "Gadiformes", "category_id" => 9]);
        Ingredients::create(["name" => "Garcinia Indica", "category_id" => 11]);
        Ingredients::create(["name" => "Garden cress", "category_id" => 13]);
        Ingredients::create(["name" => "Garfish", "category_id" => 9]);
        Ingredients::create(["name" => "Garland chrysanthemum", "category_id" => 10]);
        Ingredients::create(["name" => "Garlic", "category_id" => 13]);
        Ingredients::create(["name" => "Gefilte fish", "category_id" => 7]);
        Ingredients::create(["name" => "Gelatin", "category_id" => 1]);
        Ingredients::create(["name" => "Gelatin", "category_id" => 1]);
        Ingredients::create(["name" => "Gelatin dessert", "category_id" => 1]);
        Ingredients::create(["name" => "Geranium", "category_id" => 8]);
        Ingredients::create(["name" => "Ghee", "category_id" => 6]);
        Ingredients::create(["name" => "Giant butterbur", "category_id" => 18]);
        Ingredients::create(["name" => "Gin", "category_id" => 4]);
        Ingredients::create(["name" => "Ginger", "category_id" => 20]);
        Ingredients::create(["name" => "Ginkgo nuts", "category_id" => 17]);
        Ingredients::create(["name" => "Ginseng", "category_id" => 21]);
        Ingredients::create(["name" => "Goat Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Goat Milk", "category_id" => 6]);
        Ingredients::create(["name" => "Gooseberry", "category_id" => 11]);
        Ingredients::create(["name" => "Gram bean", "category_id" => 14]);
        Ingredients::create(["name" => "Grape", "category_id" => 11]);
        Ingredients::create(["name" => "Grapefruit", "category_id" => 11]);
        Ingredients::create(["name" => "Grapefruit Peel Oil", "category_id" => 8]);
        Ingredients::create(["name" => "Grass", "category_id" => 8]);
        Ingredients::create(["name" => "Grass pea", "category_id" => 14]);
        Ingredients::create(["name" => "Great horned owl", "category_id" => 16]);
        Ingredients::create(["name" => "Greater sturgeon", "category_id" => 9]);
        Ingredients::create(["name" => "Green Beans", "category_id" => 21]);
        Ingredients::create(["name" => "Green Tea", "category_id" => 3]);
        Ingredients::create(["name" => "Green turtle", "category_id" => 16]);
        Ingredients::create(["name" => "Green zucchini", "category_id" => 21]);
        Ingredients::create(["name" => "Greenland halibut", "category_id" => 9]);
        Ingredients::create(["name" => "Greenthread tea", "category_id" => 3]);
        Ingredients::create(["name" => "Greylag goose", "category_id" => 16]);
        Ingredients::create(["name" => "Groundcherry", "category_id" => 11]);
        Ingredients::create(["name" => "Grouper", "category_id" => 9]);
        Ingredients::create(["name" => "Gruyere Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Guava", "category_id" => 11]);
        Ingredients::create(["name" => "Guinea hen", "category_id" => 16]);
        Ingredients::create(["name" => "Haddock", "category_id" => 9]);
        Ingredients::create(["name" => "Ham", "category_id" => 16]);
        Ingredients::create(["name" => "Hamburger", "category_id" => 7]);
        Ingredients::create(["name" => "Hard wheat", "category_id" => 5]);
        Ingredients::create(["name" => "Hazelnut", "category_id" => 17]);
        Ingredients::create(["name" => "Heart of palm", "category_id" => 21]);
        Ingredients::create(["name" => "Hedge mustard", "category_id" => 21]);
        Ingredients::create(["name" => "Hibiscus tea", "category_id" => 3]);
        Ingredients::create(["name" => "Hippoglossus", "category_id" => 9]);
        Ingredients::create(["name" => "Hogplum", "category_id" => 11]);
        Ingredients::create(["name" => "Honey", "category_id" => 18]);
        Ingredients::create(["name" => "Hops", "category_id" => 18]);
        Ingredients::create(["name" => "Hops Beer", "category_id" => 4]);
        Ingredients::create(["name" => "Hops Oil", "category_id" => 8]);
        Ingredients::create(["name" => "Horchata", "category_id" => 3]);
        Ingredients::create(["name" => "Horned melon", "category_id" => 11]);
        Ingredients::create(["name" => "Horse", "category_id" => 16]);
        Ingredients::create(["name" => "Horseradish", "category_id" => 21]);
        Ingredients::create(["name" => "Hot chocolate", "category_id" => 3]);
        Ingredients::create(["name" => "Hot dog", "category_id" => 7]);
        Ingredients::create(["name" => "Hummus", "category_id" => 7]);
        Ingredients::create(["name" => "Hushpuppy", "category_id" => 7]);
        Ingredients::create(["name" => "Hyacinth", "category_id" => 8]);
        Ingredients::create(["name" => "Hyacinth bean", "category_id" => 14]);
        Ingredients::create(["name" => "Hyssop Oil", "category_id" => 8]);
        Ingredients::create(["name" => "Ice cream", "category_id" => 7]);
        Ingredients::create(["name" => "Ice cream cone", "category_id" => 7]);
        Ingredients::create(["name" => "Icing", "category_id" => 1]);
        Ingredients::create(["name" => "Irish moss", "category_id" => 19]);
        Ingredients::create(["name" => "Jackfruit", "category_id" => 11]);
        Ingredients::create(["name" => "Jalapeno", "category_id" => 20]);
        Ingredients::create(["name" => "Japanese chestnut", "category_id" => 17]);
        Ingredients::create(["name" => "Japanese persimmon", "category_id" => 11]);
        Ingredients::create(["name" => "Japanese pumpkin", "category_id" => 11]);
        Ingredients::create(["name" => "Japanese Whisky", "category_id" => 4]);
        Ingredients::create(["name" => "Jasmine", "category_id" => 10]);
        Ingredients::create(["name" => "Jellyfish", "category_id" => 19]);
        Ingredients::create(["name" => "Jerusalem artichoke", "category_id" => 21]);
        Ingredients::create(["name" => "Jew's ear", "category_id" => 12]);
        Ingredients::create(["name" => "Jicama", "category_id" => 21]);
        Ingredients::create(["name" => "Jostaberry", "category_id" => 11]);
        Ingredients::create(["name" => "Jujube", "category_id" => 11]);
        Ingredients::create(["name" => "Junket", "category_id" => 6]);
        Ingredients::create(["name" => "Jute", "category_id" => 18]);
        Ingredients::create(["name" => "Kai lan", "category_id" => 21]);
        Ingredients::create(["name" => "Kale", "category_id" => 21]);
        Ingredients::create(["name" => "Kefir", "category_id" => 6]);
        Ingredients::create(["name" => "Kelp", "category_id" => 19]);
        Ingredients::create(["name" => "Kenaf", "category_id" => 8]);
        Ingredients::create(["name" => "Ketchup", "category_id" => 1]);
        Ingredients::create(["name" => "Kewda", "category_id" => 8]);
        Ingredients::create(["name" => "Kidney Beans", "category_id" => 14]);
        Ingredients::create(["name" => "King mackerel", "category_id" => 9]);
        Ingredients::create(["name" => "Kiwifruit", "category_id" => 11]);
        Ingredients::create(["name" => "Kohlrabi", "category_id" => 21]);
        Ingredients::create(["name" => "Komatsuna", "category_id" => 21]);
        Ingredients::create(["name" => "Kombu", "category_id" => 19]);
        Ingredients::create(["name" => "Krill", "category_id" => 19]);
        Ingredients::create(["name" => "Kumquat", "category_id" => 11]);
        Ingredients::create(["name" => "Lake trout", "category_id" => 9]);
        Ingredients::create(["name" => "Lamb", "category_id" => 16]);
        Ingredients::create(["name" => "Lambsquarters", "category_id" => 18]);
        Ingredients::create(["name" => "Lard", "category_id" => 16]);
        Ingredients::create(["name" => "Lasagna", "category_id" => 7]);
        Ingredients::create(["name" => "Laurel", "category_id" => 18]);
        Ingredients::create(["name" => "Lavendar", "category_id" => 10]);
        Ingredients::create(["name" => "Lean Fish", "category_id" => 9]);
        Ingredients::create(["name" => "Leather chiton", "category_id" => 19]);
        Ingredients::create(["name" => "Leavening agent", "category_id" => 1]);
        Ingredients::create(["name" => "Leek", "category_id" => 21]);
        Ingredients::create(["name" => "Lemon", "category_id" => 11]);
        Ingredients::create(["name" => "Lemon Balm", "category_id" => 13]);
        Ingredients::create(["name" => "Lemon Grass", "category_id" => 8]);
        Ingredients::create(["name" => "Lemon Juice", "category_id" => 3]);
        Ingredients::create(["name" => "Lemon Peel Oil", "category_id" => 8]);
        Ingredients::create(["name" => "Lemon sole", "category_id" => 9]);
        Ingredients::create(["name" => "Lemon verbena", "category_id" => 13]);
        Ingredients::create(["name" => "Lentils", "category_id" => 14]);
        Ingredients::create(["name" => "Lettuce", "category_id" => 21]);
        Ingredients::create(["name" => "Lima Beans", "category_id" => 14]);
        Ingredients::create(["name" => "Limburger Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Lime", "category_id" => 11]);
        Ingredients::create(["name" => "Lime Peel Oil", "category_id" => 8]);
        Ingredients::create(["name" => "Linden", "category_id" => 13]);
        Ingredients::create(["name" => "Lingcod", "category_id" => 9]);
        Ingredients::create(["name" => "Lingonberry", "category_id" => 11]);
        Ingredients::create(["name" => "Liqourice", "category_id" => 13]);
        Ingredients::create(["name" => "Liquid Smoke", "category_id" => 1]);
        Ingredients::create(["name" => "Litchi", "category_id" => 11]);
        Ingredients::create(["name" => "Lobster", "category_id" => 19]);
        Ingredients::create(["name" => "Loganberry", "category_id" => 11]);
        Ingredients::create(["name" => "Longan", "category_id" => 18]);
        Ingredients::create(["name" => "Loquat", "category_id" => 11]);
        Ingredients::create(["name" => "Lotus", "category_id" => 8]);
        Ingredients::create(["name" => "Lovage", "category_id" => 8]);
        Ingredients::create(["name" => "Lumpsucker", "category_id" => 9]);
        Ingredients::create(["name" => "Lupine", "category_id" => 18]);
        Ingredients::create(["name" => "Macadamia Nut", "category_id" => 17]);
        Ingredients::create(["name" => "Macaroni", "category_id" => 18]);
        Ingredients::create(["name" => "Mace", "category_id" => 20]);
        Ingredients::create(["name" => "Madeira wine", "category_id" => 4]);
        Ingredients::create(["name" => "Maitake", "category_id" => 12]);
        Ingredients::create(["name" => "Malabar plum", "category_id" => 11]);
        Ingredients::create(["name" => "Malabar spinach", "category_id" => 21]);
        Ingredients::create(["name" => "Malay Apple", "category_id" => 11]);
        Ingredients::create(["name" => "Malt", "category_id" => 5]);
        Ingredients::create(["name" => "Malt Whisky", "category_id" => 4]);
        Ingredients::create(["name" => "Mammee apple", "category_id" => 11]);
        Ingredients::create(["name" => "Mandarin Orange", "category_id" => 11]);
        Ingredients::create(["name" => "Mandarin Orange Peel Oil", "category_id" => 8]);
        Ingredients::create(["name" => "Mango", "category_id" => 11]);
        Ingredients::create(["name" => "Margarine", "category_id" => 1]);
        Ingredients::create(["name" => "Marjoram", "category_id" => 20]);
        Ingredients::create(["name" => "Marshmallow", "category_id" => 2]);
        Ingredients::create(["name" => "Marzipan", "category_id" => 7]);
        Ingredients::create(["name" => "Mastic Gum", "category_id" => 8]);
        Ingredients::create(["name" => "Mate", "category_id" => 3]);
        Ingredients::create(["name" => "Meat", "category_id" => 16]);
        Ingredients::create(["name" => "Meat bouillon", "category_id" => 7]);
        Ingredients::create(["name" => "Meatball", "category_id" => 7]);
        Ingredients::create(["name" => "Meatloaf", "category_id" => 7]);
        Ingredients::create(["name" => "Medlar", "category_id" => 11]);
        Ingredients::create(["name" => "Melon", "category_id" => 11]);
        Ingredients::create(["name" => "Mentha Oil", "category_id" => 8]);
        Ingredients::create(["name" => "Meringue", "category_id" => 2]);
        Ingredients::create(["name" => "Mexican groundcherry", "category_id" => 11]);
        Ingredients::create(["name" => "Mexican oregano", "category_id" => 13]);
        Ingredients::create(["name" => "Milk", "category_id" => 6]);
        Ingredients::create(["name" => "Milk Fat", "category_id" => 6]);
        Ingredients::create(["name" => "Milk Human", "category_id" => 6]);
        Ingredients::create(["name" => "Milk Powder", "category_id" => 6]);
        Ingredients::create(["name" => "Milkfish", "category_id" => 9]);
        Ingredients::create(["name" => "Milkshake", "category_id" => 3]);
        Ingredients::create(["name" => "Millet", "category_id" => 14]);
        Ingredients::create(["name" => "Mint", "category_id" => 13]);
        Ingredients::create(["name" => "Miso", "category_id" => 1]);
        Ingredients::create(["name" => "Mixed nuts", "category_id" => 17]);
        Ingredients::create(["name" => "Molasses", "category_id" => 1]);
        Ingredients::create(["name" => "Mollusc", "category_id" => 19]);
        Ingredients::create(["name" => "Monkfish", "category_id" => 9]);
        Ingredients::create(["name" => "Monosodium Glutamate", "category_id" => 1]);
        Ingredients::create(["name" => "Moose", "category_id" => 16]);
        Ingredients::create(["name" => "Morchella", "category_id" => 12]);
        Ingredients::create(["name" => "Moth bean", "category_id" => 14]);
        Ingredients::create(["name" => "Mountain hare", "category_id" => 16]);
        Ingredients::create(["name" => "Mountain Papaya", "category_id" => 11]);
        Ingredients::create(["name" => "Mountain yam", "category_id" => 21]);
        Ingredients::create(["name" => "Mozzarella Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Mulberry", "category_id" => 11]);
        Ingredients::create(["name" => "Mule deer", "category_id" => 16]);
        Ingredients::create(["name" => "Multigrain bread", "category_id" => 2]);
        Ingredients::create(["name" => "Mung bean", "category_id" => 14]);
        Ingredients::create(["name" => "Munster Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Muscadine grape", "category_id" => 11]);
        Ingredients::create(["name" => "Mushroom", "category_id" => 12]);
        Ingredients::create(["name" => "Musk Melon", "category_id" => 11]);
        Ingredients::create(["name" => "Muskmallow", "category_id" => 17]);
        Ingredients::create(["name" => "Muskrat", "category_id" => 16]);
        Ingredients::create(["name" => "Mustard", "category_id" => 21]);
        Ingredients::create(["name" => "Mustard Oil", "category_id" => 18]);
        Ingredients::create(["name" => "Mutton", "category_id" => 16]);
        Ingredients::create(["name" => "Myrrh", "category_id" => 8]);
        Ingredients::create(["name" => "Myrtle", "category_id" => 18]);
        Ingredients::create(["name" => "Nachos", "category_id" => 7]);
        Ingredients::create(["name" => "Nance", "category_id" => 11]);
        Ingredients::create(["name" => "Nanking cherry", "category_id" => 11]);
        Ingredients::create(["name" => "Naranjilla", "category_id" => 11]);
        Ingredients::create(["name" => "Narrowleaf cattail", "category_id" => 13]);
        Ingredients::create(["name" => "Natal plum", "category_id" => 11]);
        Ingredients::create(["name" => "Natto", "category_id" => 7]);
        Ingredients::create(["name" => "Neroli Oil", "category_id" => 8]);
        Ingredients::create(["name" => "New Zealand spinach", "category_id" => 21]);
        Ingredients::create(["name" => "Nigella Seed", "category_id" => 17]);
        Ingredients::create(["name" => "Nopal", "category_id" => 18]);
        Ingredients::create(["name" => "North Pacific giant octopus", "category_id" => 19]);
        Ingredients::create(["name" => "Northern bluefin tuna", "category_id" => 9]);
        Ingredients::create(["name" => "Northern pike", "category_id" => 9]);
        Ingredients::create(["name" => "Norway haddock", "category_id" => 9]);
        Ingredients::create(["name" => "Norway pout", "category_id" => 9]);
        Ingredients::create(["name" => "Nougat", "category_id" => 7]);
        Ingredients::create(["name" => "Nutmeg", "category_id" => 20]);
        Ingredients::create(["name" => "Nuttall cockle", "category_id" => 9]);
        Ingredients::create(["name" => "Oat bread", "category_id" => 2]);
        Ingredients::create(["name" => "Oats", "category_id" => 5]);
        Ingredients::create(["name" => "Ocean pout", "category_id" => 9]);
        Ingredients::create(["name" => "Ohelo berry", "category_id" => 11]);
        Ingredients::create(["name" => "Oil palm", "category_id" => 18]);
        Ingredients::create(["name" => "Oil-seed Camellia", "category_id" => 18]);
        Ingredients::create(["name" => "Okra", "category_id" => 21]);
        Ingredients::create(["name" => "Olive", "category_id" => 18]);
        Ingredients::create(["name" => "Onion", "category_id" => 21]);
        Ingredients::create(["name" => "Opossum", "category_id" => 16]);
        Ingredients::create(["name" => "Orange", "category_id" => 11]);
        Ingredients::create(["name" => "Orange Oil", "category_id" => 8]);
        Ingredients::create(["name" => "Orange roughy", "category_id" => 9]);
        Ingredients::create(["name" => "Oregano", "category_id" => 20]);
        Ingredients::create(["name" => "Oregon yampah", "category_id" => 18]);
        Ingredients::create(["name" => "Oriental wheat", "category_id" => 5]);
        Ingredients::create(["name" => "Orris", "category_id" => 8]);
        Ingredients::create(["name" => "Ostrich", "category_id" => 16]);
        Ingredients::create(["name" => "Ostrich fern", "category_id" => 18]);
        Ingredients::create(["name" => "Oyster", "category_id" => 19]);
        Ingredients::create(["name" => "Oyster mushroom", "category_id" => 12]);
        Ingredients::create(["name" => "Pacific herring", "category_id" => 9]);
        Ingredients::create(["name" => "Pacific jack mackerel", "category_id" => 9]);
        Ingredients::create(["name" => "Pacific ocean perch", "category_id" => 9]);
        Ingredients::create(["name" => "Pacific rockfish", "category_id" => 9]);
        Ingredients::create(["name" => "Pacific sardine", "category_id" => 9]);
        Ingredients::create(["name" => "Painted comber", "category_id" => 9]);
        Ingredients::create(["name" => "Pak choy", "category_id" => 21]);
        Ingredients::create(["name" => "Pan dulce", "category_id" => 2]);
        Ingredients::create(["name" => "Pancake", "category_id" => 7]);
        Ingredients::create(["name" => "Paneer", "category_id" => 6]);
        Ingredients::create(["name" => "Papaya", "category_id" => 11]);
        Ingredients::create(["name" => "Papaya Brandy", "category_id" => 4]);
        Ingredients::create(["name" => "Parmesan Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Parsley", "category_id" => 20]);
        Ingredients::create(["name" => "Parsnip", "category_id" => 21]);
        Ingredients::create(["name" => "Passionfruit", "category_id" => 11]);
        Ingredients::create(["name" => "Pasta", "category_id" => 2]);
        Ingredients::create(["name" => "Pastry", "category_id" => 7]);
        Ingredients::create(["name" => "Pate", "category_id" => 7]);
        Ingredients::create(["name" => "Pawpaw", "category_id" => 11]);
        Ingredients::create(["name" => "Peach", "category_id" => 11]);
        Ingredients::create(["name" => "Peanut", "category_id" => 17]);
        Ingredients::create(["name" => "Peanut Butter", "category_id" => 18]);
        Ingredients::create(["name" => "Peanut Oil", "category_id" => 18]);
        Ingredients::create(["name" => "Pear", "category_id" => 11]);
        Ingredients::create(["name" => "Pear Brandy", "category_id" => 4]);
        Ingredients::create(["name" => "Peas", "category_id" => 14]);
        Ingredients::create(["name" => "Pecans", "category_id" => 17]);
        Ingredients::create(["name" => "Pectin", "category_id" => 1]);
        Ingredients::create(["name" => "Pepino", "category_id" => 11]);
        Ingredients::create(["name" => "Pepper", "category_id" => 20]);
        Ingredients::create(["name" => "Peppermint", "category_id" => 13]);
        Ingredients::create(["name" => "Perciformes", "category_id" => 9]);
        Ingredients::create(["name" => "Percoidei", "category_id" => 9]);
        Ingredients::create(["name" => "Persimmon", "category_id" => 11]);
        Ingredients::create(["name" => "Pheasant", "category_id" => 16]);
        Ingredients::create(["name" => "Phyllo dough", "category_id" => 2]);
        Ingredients::create(["name" => "Pie", "category_id" => 7]);
        Ingredients::create(["name" => "Pie crust", "category_id" => 2]);
        Ingredients::create(["name" => "Pigeon Pea", "category_id" => 14]);
        Ingredients::create(["name" => "Pikeperch", "category_id" => 9]);
        Ingredients::create(["name" => "Piki bread", "category_id" => 2]);
        Ingredients::create(["name" => "Pili nut", "category_id" => 17]);
        Ingredients::create(["name" => "Pine", "category_id" => 18]);
        Ingredients::create(["name" => "Pineapple", "category_id" => 11]);
        Ingredients::create(["name" => "Pineappple sage", "category_id" => 13]);
        Ingredients::create(["name" => "Pink salmon", "category_id" => 9]);
        Ingredients::create(["name" => "Pistachio", "category_id" => 17]);
        Ingredients::create(["name" => "Pita bread", "category_id" => 2]);
        Ingredients::create(["name" => "Pitanga", "category_id" => 11]);
        Ingredients::create(["name" => "Pizza", "category_id" => 7]);
        Ingredients::create(["name" => "Pleuronectidae", "category_id" => 9]);
        Ingredients::create(["name" => "Plum", "category_id" => 11]);
        Ingredients::create(["name" => "Plum Brandy", "category_id" => 4]);
        Ingredients::create(["name" => "Plum Wine", "category_id" => 4]);
        Ingredients::create(["name" => "Plumcot", "category_id" => 11]);
        Ingredients::create(["name" => "Polar bear", "category_id" => 16]);
        Ingredients::create(["name" => "Pollock", "category_id" => 9]);
        Ingredients::create(["name" => "Pomegranate", "category_id" => 11]);
        Ingredients::create(["name" => "Popcorn", "category_id" => 15]);
        Ingredients::create(["name" => "Poppy Seed", "category_id" => 20]);
        Ingredients::create(["name" => "Pork", "category_id" => 16]);
        Ingredients::create(["name" => "Port Wine", "category_id" => 4]);
        Ingredients::create(["name" => "Pot pie", "category_id" => 7]);
        Ingredients::create(["name" => "Potato", "category_id" => 21]);
        Ingredients::create(["name" => "Potato bread", "category_id" => 2]);
        Ingredients::create(["name" => "Potato chip", "category_id" => 2]);
        Ingredients::create(["name" => "Potato gratin", "category_id" => 7]);
        Ingredients::create(["name" => "Potato puffs", "category_id" => 7]);
        Ingredients::create(["name" => "Prairie turnip", "category_id" => 21]);
        Ingredients::create(["name" => "Prawn", "category_id" => 19]);
        Ingredients::create(["name" => "Prickly Pear", "category_id" => 11]);
        Ingredients::create(["name" => "Provolone Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Pudding", "category_id" => 7]);
        Ingredients::create(["name" => "Pummelo", "category_id" => 11]);
        Ingredients::create(["name" => "Pumpkin", "category_id" => 11]);
        Ingredients::create(["name" => "Pumpkinseed sunfish", "category_id" => 9]);
        Ingredients::create(["name" => "Pupusa", "category_id" => 7]);
        Ingredients::create(["name" => "Purple laver", "category_id" => 19]);
        Ingredients::create(["name" => "Purple mangosteen", "category_id" => 11]);
        Ingredients::create(["name" => "Purslane", "category_id" => 18]);
        Ingredients::create(["name" => "Quail", "category_id" => 16]);
        Ingredients::create(["name" => "Quesadilla", "category_id" => 7]);
        Ingredients::create(["name" => "Quince", "category_id" => 11]);
        Ingredients::create(["name" => "Quinoa", "category_id" => 5]);
        Ingredients::create(["name" => "Rabbit", "category_id" => 16]);
        Ingredients::create(["name" => "Raccoon", "category_id" => 16]);
        Ingredients::create(["name" => "Radish", "category_id" => 21]);
        Ingredients::create(["name" => "Rainbow smelt", "category_id" => 9]);
        Ingredients::create(["name" => "Rainbow trout", "category_id" => 9]);
        Ingredients::create(["name" => "Raisin", "category_id" => 11]);
        Ingredients::create(["name" => "Raisin bread", "category_id" => 2]);
        Ingredients::create(["name" => "Rambutan", "category_id" => 11]);
        Ingredients::create(["name" => "Rapini", "category_id" => 21]);
        Ingredients::create(["name" => "Raspberry", "category_id" => 11]);
        Ingredients::create(["name" => "Raspberry Brandy", "category_id" => 4]);
        Ingredients::create(["name" => "Ravioli", "category_id" => 7]);
        Ingredients::create(["name" => "Red algae", "category_id" => 19]);
        Ingredients::create(["name" => "Red Currant", "category_id" => 11]);
        Ingredients::create(["name" => "Red king crab", "category_id" => 19]);
        Ingredients::create(["name" => "Red raspberry", "category_id" => 11]);
        Ingredients::create(["name" => "Red rice", "category_id" => 5]);
        Ingredients::create(["name" => "Red Sage", "category_id" => 8]);
        Ingredients::create(["name" => "Red Wine", "category_id" => 4]);
        Ingredients::create(["name" => "Redskin onion", "category_id" => 21]);
        Ingredients::create(["name" => "Relish", "category_id" => 7]);
        Ingredients::create(["name" => "Remoulade", "category_id" => 7]);
        Ingredients::create(["name" => "Rhubarb", "category_id" => 13]);
        Ingredients::create(["name" => "Rice", "category_id" => 5]);
        Ingredients::create(["name" => "Rice bread", "category_id" => 2]);
        Ingredients::create(["name" => "Rice cake", "category_id" => 7]);
        Ingredients::create(["name" => "Ricotta Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Ringed seal", "category_id" => 19]);
        Ingredients::create(["name" => "Rock ptarmigan", "category_id" => 16]);
        Ingredients::create(["name" => "Rocket salad", "category_id" => 13]);
        Ingredients::create(["name" => "Roe", "category_id" => 9]);
        Ingredients::create(["name" => "Roibos Tea", "category_id" => 3]);
        Ingredients::create(["name" => "Romano Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Roquefort Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Rose", "category_id" => 10]);
        Ingredients::create(["name" => "Rose hip", "category_id" => 11]);
        Ingredients::create(["name" => "Rose Wine", "category_id" => 4]);
        Ingredients::create(["name" => "Roseapple", "category_id" => 11]);
        Ingredients::create(["name" => "Roselle", "category_id" => 13]);
        Ingredients::create(["name" => "Rosemary", "category_id" => 13]);
        Ingredients::create(["name" => "Rowal", "category_id" => 18]);
        Ingredients::create(["name" => "Rowanberry", "category_id" => 11]);
        Ingredients::create(["name" => "Rum", "category_id" => 4]);
        Ingredients::create(["name" => "Russian Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Rutabaga", "category_id" => 21]);
        Ingredients::create(["name" => "Rye", "category_id" => 5]);
        Ingredients::create(["name" => "Rye Bread", "category_id" => 2]);
        Ingredients::create(["name" => "Sablefish", "category_id" => 9]);
        Ingredients::create(["name" => "Safflower", "category_id" => 13]);
        Ingredients::create(["name" => "Saffron", "category_id" => 20]);
        Ingredients::create(["name" => "Sage", "category_id" => 13]);
        Ingredients::create(["name" => "Sago palm", "category_id" => 18]);
        Ingredients::create(["name" => "Sake", "category_id" => 4]);
        Ingredients::create(["name" => "Salad", "category_id" => 7]);
        Ingredients::create(["name" => "Salad dressing", "category_id" => 7]);
        Ingredients::create(["name" => "Salmon", "category_id" => 9]);
        Ingredients::create(["name" => "Salmonberry", "category_id" => 11]);
        Ingredients::create(["name" => "Salmonidae", "category_id" => 9]);
        Ingredients::create(["name" => "Salt", "category_id" => 1]);
        Ingredients::create(["name" => "Sandalwood", "category_id" => 8]);
        Ingredients::create(["name" => "Sapodilla", "category_id" => 11]);
        Ingredients::create(["name" => "Saskatoon berry", "category_id" => 11]);
        Ingredients::create(["name" => "Sassafras", "category_id" => 18]);
        Ingredients::create(["name" => "Satsuma Orange", "category_id" => 11]);
        Ingredients::create(["name" => "Sauerkraut", "category_id" => 21]);
        Ingredients::create(["name" => "Sausage", "category_id" => 7]);
        Ingredients::create(["name" => "Scallop", "category_id" => 19]);
        Ingredients::create(["name" => "Scarlet bean", "category_id" => 14]);
        Ingredients::create(["name" => "Scombridae", "category_id" => 9]);
        Ingredients::create(["name" => "Scotch", "category_id" => 4]);
        Ingredients::create(["name" => "Scotch Spearmint", "category_id" => 13]);
        Ingredients::create(["name" => "Scrapple", "category_id" => 7]);
        Ingredients::create(["name" => "Scup", "category_id" => 9]);
        Ingredients::create(["name" => "Sea Buckthorns", "category_id" => 11]);
        Ingredients::create(["name" => "Sea cucumber", "category_id" => 19]);
        Ingredients::create(["name" => "Sea trout", "category_id" => 9]);
        Ingredients::create(["name" => "Semolina", "category_id" => 5]);
        Ingredients::create(["name" => "Sesame", "category_id" => 17]);
        Ingredients::create(["name" => "Sesbania flower", "category_id" => 10]);
        Ingredients::create(["name" => "Shallot", "category_id" => 21]);
        Ingredients::create(["name" => "Shark", "category_id" => 9]);
        Ingredients::create(["name" => "Shea tree", "category_id" => 18]);
        Ingredients::create(["name" => "Sheefish", "category_id" => 9]);
        Ingredients::create(["name" => "Sheep Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Sheep Milk", "category_id" => 6]);
        Ingredients::create(["name" => "Sheepshead", "category_id" => 9]);
        Ingredients::create(["name" => "Shellfish", "category_id" => 19]);
        Ingredients::create(["name" => "Sherry", "category_id" => 4]);
        Ingredients::create(["name" => "Shiitake", "category_id" => 12]);
        Ingredients::create(["name" => "Shortening", "category_id" => 1]);
        Ingredients::create(["name" => "Shrimp", "category_id" => 19]);
        Ingredients::create(["name" => "Silver linden", "category_id" => 13]);
        Ingredients::create(["name" => "Skimmed Milk", "category_id" => 6]);
        Ingredients::create(["name" => "Skunk currant", "category_id" => 11]);
        Ingredients::create(["name" => "Small leaf linden", "category_id" => 18]);
        Ingredients::create(["name" => "Smelt", "category_id" => 9]);
        Ingredients::create(["name" => "Smoked Fish", "category_id" => 9]);
        Ingredients::create(["name" => "Snack bar", "category_id" => 7]);
        Ingredients::create(["name" => "Snail", "category_id" => 16]);
        Ingredients::create(["name" => "Snapper", "category_id" => 9]);
        Ingredients::create(["name" => "Sockeye salmon", "category_id" => 9]);
        Ingredients::create(["name" => "Soft drink", "category_id" => 3]);
        Ingredients::create(["name" => "Sorghum", "category_id" => 5]);
        Ingredients::create(["name" => "Sorrel", "category_id" => 13]);
        Ingredients::create(["name" => "Soup", "category_id" => 7]);
        Ingredients::create(["name" => "Sour Cherry", "category_id" => 11]);
        Ingredients::create(["name" => "Sourdock", "category_id" => 13]);
        Ingredients::create(["name" => "Sourdough", "category_id" => 5]);
        Ingredients::create(["name" => "Soursop", "category_id" => 11]);
        Ingredients::create(["name" => "Soy cream", "category_id" => 7]);
        Ingredients::create(["name" => "Soy milk", "category_id" => 3]);
        Ingredients::create(["name" => "Soy yogurt", "category_id" => 18]);
        Ingredients::create(["name" => "Soybean", "category_id" => 14]);
        Ingredients::create(["name" => "Soybean Oil", "category_id" => 14]);
        Ingredients::create(["name" => "Soybean Sauce", "category_id" => 18]);
        Ingredients::create(["name" => "Spanish mackerel", "category_id" => 9]);
        Ingredients::create(["name" => "Spanish Sage", "category_id" => 8]);
        Ingredients::create(["name" => "Sparkleberry", "category_id" => 11]);
        Ingredients::create(["name" => "Sparkling Wine", "category_id" => 4]);
        Ingredients::create(["name" => "Spearmint", "category_id" => 13]);
        Ingredients::create(["name" => "Spelt", "category_id" => 5]);
        Ingredients::create(["name" => "Spinach", "category_id" => 21]);
        Ingredients::create(["name" => "Spineless Monkey Orange", "category_id" => 11]);
        Ingredients::create(["name" => "Spiny dogfish", "category_id" => 9]);
        Ingredients::create(["name" => "Spiny lobster", "category_id" => 19]);
        Ingredients::create(["name" => "Spirit", "category_id" => 4]);
        Ingredients::create(["name" => "Spirulina", "category_id" => 1]);
        Ingredients::create(["name" => "Spot croaker", "category_id" => 9]);
        Ingredients::create(["name" => "Spotted seal", "category_id" => 19]);
        Ingredients::create(["name" => "Spread", "category_id" => 1]);
        Ingredients::create(["name" => "Squab", "category_id" => 16]);
        Ingredients::create(["name" => "Squashberry", "category_id" => 11]);
        Ingredients::create(["name" => "Squid", "category_id" => 19]);
        Ingredients::create(["name" => "Squirrel", "category_id" => 16]);
        Ingredients::create(["name" => "Star Anise", "category_id" => 20]);
        Ingredients::create(["name" => "Starfruit", "category_id" => 11]);
        Ingredients::create(["name" => "Steller sea lion", "category_id" => 19]);
        Ingredients::create(["name" => "Stew", "category_id" => 7]);
        Ingredients::create(["name" => "Storax", "category_id" => 18]);
        Ingredients::create(["name" => "Strawberry", "category_id" => 11]);
        Ingredients::create(["name" => "Strawberry Jam", "category_id" => 11]);
        Ingredients::create(["name" => "Strawberry Wine", "category_id" => 4]);
        Ingredients::create(["name" => "Striped bass", "category_id" => 9]);
        Ingredients::create(["name" => "Striped mullet", "category_id" => 9]);
        Ingredients::create(["name" => "Stuffing", "category_id" => 1]);
        Ingredients::create(["name" => "Sturgeon", "category_id" => 9]);
        Ingredients::create(["name" => "Succotash", "category_id" => 7]);
        Ingredients::create(["name" => "Sugar", "category_id" => 1]);
        Ingredients::create(["name" => "Sukiyaki", "category_id" => 16]);
        Ingredients::create(["name" => "Summer savory", "category_id" => 13]);
        Ingredients::create(["name" => "Sunflower", "category_id" => 10]);
        Ingredients::create(["name" => "Swamp cabbage", "category_id" => 21]);
        Ingredients::create(["name" => "Sweet Cherry", "category_id" => 11]);
        Ingredients::create(["name" => "Sweet custard", "category_id" => 6]);
        Ingredients::create(["name" => "Sweet Grass", "category_id" => 8]);
        Ingredients::create(["name" => "Sweet Potato", "category_id" => 21]);
        Ingredients::create(["name" => "Sweetcorn", "category_id" => 15]);
        Ingredients::create(["name" => "Swiss Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Swordfish", "category_id" => 9]);
        Ingredients::create(["name" => "Syrup", "category_id" => 1]);
        Ingredients::create(["name" => "Taco", "category_id" => 7]);
        Ingredients::create(["name" => "Tamale", "category_id" => 7]);
        Ingredients::create(["name" => "Tamarind", "category_id" => 11]);
        Ingredients::create(["name" => "Tangerine", "category_id" => 11]);
        Ingredients::create(["name" => "Tapioca pearl", "category_id" => 21]);
        Ingredients::create(["name" => "Taro", "category_id" => 21]);
        Ingredients::create(["name" => "Tarragon", "category_id" => 13]);
        Ingredients::create(["name" => "Tartary buckwheat", "category_id" => 5]);
        Ingredients::create(["name" => "Tea", "category_id" => 18]);
        Ingredients::create(["name" => "Tea leaf willow", "category_id" => 13]);
        Ingredients::create(["name" => "Teff", "category_id" => 13]);
        Ingredients::create(["name" => "Tequila", "category_id" => 4]);
        Ingredients::create(["name" => "Thistle", "category_id" => 18]);
        Ingredients::create(["name" => "Thyme", "category_id" => 13]);
        Ingredients::create(["name" => "Tilefish", "category_id" => 9]);
        Ingredients::create(["name" => "Tilsit Cheese", "category_id" => 6]);
        Ingredients::create(["name" => "Tinda", "category_id" => 21]);
        Ingredients::create(["name" => "Tobacco", "category_id" => 18]);
        Ingredients::create(["name" => "Toffee", "category_id" => 7]);
        Ingredients::create(["name" => "Tofu", "category_id" => 18]);
        Ingredients::create(["name" => "Tomato", "category_id" => 21]);
        Ingredients::create(["name" => "Tomato Juice", "category_id" => 3]);
        Ingredients::create(["name" => "Tomato Paste", "category_id" => 21]);
        Ingredients::create(["name" => "Tomato Puree", "category_id" => 21]);
        Ingredients::create(["name" => "Topping", "category_id" => 1]);
        Ingredients::create(["name" => "Tortilla", "category_id" => 7]);
        Ingredients::create(["name" => "Tortilla chip", "category_id" => 2]);
        Ingredients::create(["name" => "Tostada", "category_id" => 7]);
        Ingredients::create(["name" => "Towel gourd", "category_id" => 21]);
        Ingredients::create(["name" => "Trail mix", "category_id" => 7]);
        Ingredients::create(["name" => "Trassi", "category_id" => 19]);
        Ingredients::create(["name" => "Tree fern", "category_id" => 18]);
        Ingredients::create(["name" => "Triticale", "category_id" => 5]);
        Ingredients::create(["name" => "True frog", "category_id" => 16]);
        Ingredients::create(["name" => "True seal", "category_id" => 19]);
        Ingredients::create(["name" => "True sole", "category_id" => 9]);
        Ingredients::create(["name" => "Truffle", "category_id" => 12]);
        Ingredients::create(["name" => "Turbot", "category_id" => 9]);
        Ingredients::create(["name" => "Turkey", "category_id" => 16]);
        Ingredients::create(["name" => "Turkey Berry", "category_id" => 21]);
        Ingredients::create(["name" => "Turmeric", "category_id" => 20]);
        Ingredients::create(["name" => "Turnip", "category_id" => 21]);
        Ingredients::create(["name" => "Ucuhuba", "category_id" => 18]);
        Ingredients::create(["name" => "Valerian", "category_id" => 8]);
        Ingredients::create(["name" => "Vanilla", "category_id" => 11]);
        Ingredients::create(["name" => "Vegetable juice", "category_id" => 3]);
        Ingredients::create(["name" => "Vermouth", "category_id" => 4]);
        Ingredients::create(["name" => "Vinegar", "category_id" => 18]);
        Ingredients::create(["name" => "Vodka", "category_id" => 4]);
        Ingredients::create(["name" => "Waffle", "category_id" => 7]);
        Ingredients::create(["name" => "Wakame", "category_id" => 19]);
        Ingredients::create(["name" => "Walleye", "category_id" => 9]);
        Ingredients::create(["name" => "Walnut", "category_id" => 17]);
        Ingredients::create(["name" => "Walrus", "category_id" => 19]);
        Ingredients::create(["name" => "Wasabi", "category_id" => 21]);
        Ingredients::create(["name" => "Water", "category_id" => 1]);
        Ingredients::create(["name" => "Water Chestnut", "category_id" => 11]);
        Ingredients::create(["name" => "Watercress", "category_id" => 18]);
        Ingredients::create(["name" => "Wattle", "category_id" => 8]);
        Ingredients::create(["name" => "Weinbrand Brandy", "category_id" => 4]);
        Ingredients::create(["name" => "Welsh onion", "category_id" => 21]);
        Ingredients::create(["name" => "Wheat", "category_id" => 5]);
        Ingredients::create(["name" => "Wheaten Bread", "category_id" => 2]);
        Ingredients::create(["name" => "Whelk", "category_id" => 19]);
        Ingredients::create(["name" => "Whey", "category_id" => 6]);
        Ingredients::create(["name" => "Whisky", "category_id" => 4]);
        Ingredients::create(["name" => "White Bread", "category_id" => 2]);
        Ingredients::create(["name" => "White Currant", "category_id" => 11]);
        Ingredients::create(["name" => "White lupine", "category_id" => 18]);
        Ingredients::create(["name" => "White Pepper", "category_id" => 20]);
        Ingredients::create(["name" => "White sucker", "category_id" => 9]);
        Ingredients::create(["name" => "White Wine", "category_id" => 4]);
        Ingredients::create(["name" => "Whitefish", "category_id" => 9]);
        Ingredients::create(["name" => "Whiting", "category_id" => 9]);
        Ingredients::create(["name" => "Wholewheat Bread", "category_id" => 2]);
        Ingredients::create(["name" => "Wild boar", "category_id" => 16]);
        Ingredients::create(["name" => "Wild duck", "category_id" => 16]);
        Ingredients::create(["name" => "Wild rice", "category_id" => 5]);
        Ingredients::create(["name" => "Wine", "category_id" => 4]);
        Ingredients::create(["name" => "Winged bean", "category_id" => 14]);
        Ingredients::create(["name" => "Winter savory", "category_id" => 13]);
        Ingredients::create(["name" => "Winter squash", "category_id" => 11]);
        Ingredients::create(["name" => "Wonton wrapper", "category_id" => 2]);
        Ingredients::create(["name" => "Woodapple", "category_id" => 11]);
        Ingredients::create(["name" => "Wort", "category_id" => 3]);
        Ingredients::create(["name" => "Yam", "category_id" => 21]);
        Ingredients::create(["name" => "Yardlong bean", "category_id" => 14]);
        Ingredients::create(["name" => "Yarrow", "category_id" => 8]);
        Ingredients::create(["name" => "Yautia", "category_id" => 18]);
        Ingredients::create(["name" => "Yeast", "category_id" => 12]);
        Ingredients::create(["name" => "Yellow Passionfruit", "category_id" => 11]);
        Ingredients::create(["name" => "Yellow pond lily", "category_id" => 18]);
        Ingredients::create(["name" => "Yellowfin tuna", "category_id" => 9]);
        Ingredients::create(["name" => "Yellowtail amberjack", "category_id" => 9]);
        Ingredients::create(["name" => "Ylang-Ylang", "category_id" => 8]);
        Ingredients::create(["name" => "Ymer", "category_id" => 6]);
        Ingredients::create(["name" => "Yogurt", "category_id" => 6]);
        Ingredients::create(["name" => "Zucchini", "category_id" => 21]);
        Ingredients::create(["name" => "Zwieback", "category_id" => 7]);
    }
}
